name: type-class-morphisms
version: 0.1.0.0
dependencies:
  - base
ghc-options: -Wall
  
library:
  source-dirs: src/

tests:
   type-class-morphisms-test:
    main: Spec.hs
    source-dirs: test/
    dependencies:
       type-class-morphisms
